var age = 45;
console.log("age is " + age);
var name2 = "sachin";
console.log("name  " + name2);
var available = true;
console.log("availability " + available);
var fruits = ["apple", "banana", "kiwi"];
console.log(fruits);
var fruits1 = ["apple", "banana", "kiwi", 1, 2, 3];
console.log(fruits1);
var msg = (["sudeep", true, 556]);
console.log(msg);
